// React/intuit-net-worth-calculator/src/AssetRow/AssetRow.js
import React from 'react';
import './AssetRow.css'

class AssetRow extends React.Component {
    constructor(props) {
        super(props);
        this.handleChange = this.handleChange.bind(this);
    }

    handleChange(event) {
        this.props.onAssetChange(event, this.props.index);
    }

    render() {
        return (
            <tr>
                <td colSpan='2'>{this.props.asset.lineItem}</td>
                <td className='line-item-amount'>
                    <div className='row'>
                    <div>{this.props.currency.currencySymbol}</div>
                    <div className='fill-remaining-space'></div>
                    <input value={this.props.asset.amount.toFixed(2)} name={this.props.asset.lineItem} onChange={this.handleChange}></input>
                    </div>
                </td>
            </tr>
        );
    }
}

export default AssetRow;

// Angular/intuit-net-worth-calculator/src/app/component/asset-row/asset-row.component.ts
import { NetWorthService } from './../../service/net-worth/net-worth.service';
import { Asset } from './../../domain/asset';
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-asset-row',
  templateUrl: './asset-row.component.html',
  styleUrls: ['./asset-row.component.css']
})
export class AssetRowComponent implements OnInit {

  @Input()
  asset: Asset;

  constructor(public netWorthService: NetWorthService) { }

  ngOnInit() {
  }

}

<tr>
  <td colspan="2">{{asset.lineItem}}</td>
  <td class="line-item-amount">
    <div class="row">
      <div>{{netWorthService.netWorth.currency.currencySymbol}}</div>
      <div class="fill-remaining-space"></div>
      <div><input [(ngModel)]='asset.amount'/></div>
    </div>
  </td>
</tr>
